apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notifications-service-deployment
labels:
  {{- include "notifications-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "notifications-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notifications-service.labels" . | nindent 8 }}
    spec:
      {{- include "postgresql.waitForDatabase" . | nindent 6 }}
      containers:
        - name: notification-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5052
          volumeMounts:
            - name: firebase-credentials
              mountPath: /etc/firebase
              readOnly: true
          env:
            {{- include "notifications-service.env" . | nindent 12 }}
      volumes:
        - name: firebase-credentials
          secret:
            secretName: {{ .Release.Name }}-notifications-service-firebase-secrets
            items:
            - key: service-account.json
              path: service-account.json
