apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifications-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5052
  selector:
  {{- include "notifications-service.labels" . | nindent  4}}